name: Publish packages to GitHub Packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Enviroments
        run: echo ${{ secrets.GPR_USERNAME }}
      - uses: actions/checkout@v2
      - name: Set up JAVA
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_USERNAME: ${{ secrets.GPR_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
